"""empty message

Revision ID: 62dbeedf7457
Revises: 
Create Date: 2020-09-11 20:30:05.449871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62dbeedf7457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    op.drop_table('balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('eyobalance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('users',
    sa.Column('fname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_table('users2')
    # ### end Alembic commands ###
